# Export, extracts, commits, and pushes to source control the solution called SparkCode.
# Generates an artifact with the exported solution zip file

name: Save SparkCode
run-name: Save SparkCode ${{ github.event.inputs.commit_message }}

on:
  workflow_dispatch:
    inputs:
      commit_message:
        description: Commit Message. Include task IDs here.
        required: true
      create_tag:
        type: boolean
        description: Tick this box to create a tag after commit.
        default: false
  
permissions:
  id-token: write   # Required for OIDC authentication
  contents: write

jobs:

  export-and-save-solution:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4

    - name: Expose input vars
      shell: pwsh
      run: |
        Write-Output "Exposing input vars"
        echo "COMMIT_MESSAGE=${{ github.event.inputs.commit_message }}" >> $env:GITHUB_ENV
        echo "CREATE_TAG=${{ github.event.inputs.create_tag }}" >> $env:GITHUB_ENV

    - name: Export and Save Solution
      uses: ./../.github/workflows/export-and-save-solution.yml
      with:
        solution_name: SparkCode
        version_update_strategy: revision
        export_folder: out/export/
        solutions_folder: PowerPlatform/solutions/
        commit_message: ${{ env.COMMIT_MESSAGE }}
        create_tag: ${{ env.CREATE_TAG }}