# Export, extracts, commits, and pushes to source control the solution called SparkCode.
# Generates an artifact with the exported solution zip file

name: Save SparkCode
run-name: Save SparkCode ${{ github.event.inputs.commit_message }}

on:
  workflow_dispatch:
    inputs:
      commit_message:
        description: Commit Message. Include task IDs here.
        required: true
      create_tag:
        type: boolean
        description: Tick this box to create a tag after commit.
        default: false
  
permissions:
  id-token: write   # Required for OIDC authentication
  contents: write
  
jobs:
  deploy:
    environment: Dev
    runs-on: windows-latest
    
    steps:
    - name: Expose env vars
      id: vars
      shell: pwsh
      run: |
        Write-Output "Exposing env vars"
        Write-Output "commit_message=${{ github.event.inputs.commit_message }}"
        Write-Output "create_tag=${{ github.event.inputs.create_tag }}"
      outputs:
        commit_message: ${{ github.event.inputs.commit_message }}
        create_tag: ${{ github.event.inputs.create_tag }}

    - name: Export and Save Solution
      needs: vars
      uses: ./.github/workflows/export-and-save-solution.yml
      with:
        solution_name: SparkCode
        version_update_strategy: revision
        export_folder: out/export/
        solutions_folder: PowerPlatform/solutions/
        commit_message: ${{ needs.vars.outputs.commit_message }}
        create_tag: ${{ needs.vars.outputs.create_tag }}